# Generated by Django 2.0.4 on 2018-11-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('data_de_criacao', models.DateField(auto_now=True)),
                ('numero_de_integrantes', models.BigIntegerField()),
                ('em_atividade', models.BigIntegerField(choices=[(0, 'Em atividade'), (1, 'Banda encerrada')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EstiloMusical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('surgimento', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField()),
                ('data_de_nascimento', models.DateField(auto_now=True)),
                ('anos_de_carreira', models.BigIntegerField()),
            ],
        ),
    ]
