# Generated by Django 2.1.3 on 2018-11-06 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='estilo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to='music.EstiloMusical'),
        ),
        migrations.AddField(
            model_name='banda',
            name='musicos',
            field=models.ManyToManyField(to='music.Musico'),
        ),
        migrations.AlterField(
            model_name='banda',
            name='em_atividade',
            field=models.IntegerField(choices=[(0, 'Em atividade'), (1, 'Banda encerrada')], default=0),
        ),
        migrations.AlterField(
            model_name='banda',
            name='numero_de_integrantes',
            field=models.IntegerField(),
        ),
    ]
